# Generated by Django 4.1.4 on 2023-01-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customer_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
