# Generated by Django 4.0.4 on 2022-12-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_product_id_customer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
